### ISSUE TITLE
aws-node-rest-api-with-dynamodb not delpoying

### ISSUE THREAD

**Issue by waltermvp** [serverless/examples#131]
Despite being able to deploy other examples that require access to S3, i get the following error on when trying to deploy 'aws-node-rest-api-with-dynamodb'

```
Serverless: Packaging service...
Serverless: Uploading CloudFormation file to S3...
 
  Serverless Error ---------------------------------------
 
     The specified bucket does not exist
 
```

**Comment by waltermvp** [comment]
FYI this started occurring yesterday or today

**Comment by waltermvp** [comment]
Also occurring with aws-node-upload-to-s3-and-postprocess. Two projects i have used the Serverless GUI with (deploying and removing)

**Comment by waltermvp** [comment]
possibly related to https://github.com/serverless/serverless/issues/1853

**Comment by waltermvp** [comment]
Also checked for any cloud formation instances on aws.console and there were none.

**Comment by DavidWells** [comment]
@waltermvp you are trying to deploy from the `serverless desktop` app or from the CLI?

**Comment by waltermvp** [comment]
@DavidWells im attempting wit both And i get the same result. One note is that the issue appears to have begun after using the GUI app a couple times

**Comment by waltermvp** [comment]
Not completely sure if it's related though

**Comment by waltermvp** [comment]
@DavidWells any ideas?

**Comment by waltermvp** [comment]
this is the exact output

``` bash
waltermvp@Walters-iMac:~/Development/Open Source/examples/aws-node-rest-api-with-dynamodb (master)$ sls deploy
Serverless: Packaging service...
Serverless: Uploading CloudFormation file to S3...
 
  Serverless Error ---------------------------------------
 
     The specified bucket does not exist
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       6.9.1
     Serverless Version: 1.11.0
 
```

**Comment by waltermvp** [comment]
@DavidWells  I've been struggling with this for some time now, no idea what could be causing this. 
Even wiped my aws account of all resources including: 
* all buckets
* deleted and created new serverless-admin IAM user 
* removed anything from cloudformation

and im still experiencing this issue. Any help or just a nudge in the right direction would be greatly appreciated.

**Comment by waltermvp** [comment]
Also see the contents of the  `cloudformation-template-create-stack.json` (it may help)

```json
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Description": "The AWS CloudFormation template for this Serverless application",
  "Resources": {
    "ServerlessDeploymentBucket": {
      "Type": "AWS::S3::Bucket"
    }
  },
  "Outputs": {
    "ServerlessDeploymentBucketName": {
      "Value": {
        "Ref": "ServerlessDeploymentBucket"
      }
    }
  }
}
```

**Comment by waltermvp** [comment]
@christophgysin any ideas?

**Comment by christophgysin** [comment]
I can't reproduce that. Does the following command provide more details?

$ SLS_DEBUG="*" sls deploy --verbose

**Comment by waltermvp** [comment]
Thanks very much for the reply. Here is the output:

```bash
$ SLS_DEBUG="*" sls deploy --verbose
Serverless: Packaging service...
Serverless: Uploading CloudFormation file to S3...
 
  Serverless Error ---------------------------------------
 
     The specified bucket does not exist
 
  Stack Trace --------------------------------------------
 
ServerlessError: The specified bucket does not exist
    at Response.req.send (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:163:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:355:18)
    at Request.callListeners (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:668:14)
    at Request.transition (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:670:12)
    at Request.callListeners (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:668:14)
    at Request.transition (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:26:10
From previous event:
    at persistentRequest (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:151:14)
    at doCall (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:130:9)
    at BbPromise (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:141:14)
From previous event:
    at persistentRequest (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:128:38)
    at AwsProvider.request (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:144:12)
    at AwsDeploy.uploadCloudFormationFile (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/uploadArtifacts.js:23:26)
From previous event:
    at AwsDeploy.uploadArtifacts (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/uploadArtifacts.js:83:8)
From previous event:
    at Object.deploy:deploy [as fn] (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:54:10)
    at BbPromise.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:210:55)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:210:22)
    at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:225:17)
    at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:97:31)
    at serverless.init.then (/usr/local/lib/node_modules/serverless/bin/serverless:23:50)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       7.3.0
     Serverless Version: 1.11.0
 
```

**Comment by christophgysin** [comment]
Can you try to rename the service and try again?

e.g.: serverless.yml
```
service: serverless-rest-api-with-dynamodb-TEST
...
```

**Comment by waltermvp** [comment]
Got farther along but still failed: (serverless-rest-api-with-dynamodb-rename):

```bash 
$ SLS_DEBUG="*" sls deploy --verbose
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
CloudFormation - CREATE_IN_PROGRESS - AWS::CloudFormation::Stack - serverless-rest-api-with-dynamodb-rename-dev
CloudFormation - CREATE_IN_PROGRESS - AWS::S3::Bucket - ServerlessDeploymentBucket
CloudFormation - CREATE_IN_PROGRESS - AWS::S3::Bucket - ServerlessDeploymentBucket
CloudFormation - CREATE_COMPLETE - AWS::S3::Bucket - ServerlessDeploymentBucket
CloudFormation - CREATE_COMPLETE - AWS::CloudFormation::Stack - serverless-rest-api-with-dynamodb-rename-dev
Serverless: Stack create finished...
Serverless: Packaging service...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading function .zip files to S3...
Serverless: Uploading service .zip file to S3 (431.03 KB)...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
CloudFormation - CREATE_COMPLETE - AWS::CloudFormation::Stack - serverless-rest-api-with-dynamodb-rename-dev
CloudFormation - UPDATE_IN_PROGRESS - AWS::CloudFormation::Stack - serverless-rest-api-with-dynamodb-rename-dev
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - ListLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::DynamoDB::Table - TodosDynamoDbTable
CloudFormation - CREATE_IN_PROGRESS - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - CreateLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::DynamoDB::Table - TodosDynamoDbTable
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - ListLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - ListLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - DeleteLogGroup
CloudFormation - CREATE_FAILED - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - UpdateLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::ApiGateway::RestApi - ApiGatewayRestApi
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - GetLogGroup
CloudFormation - CREATE_FAILED - AWS::DynamoDB::Table - TodosDynamoDbTable
CloudFormation - CREATE_FAILED - AWS::Logs::LogGroup - DeleteLogGroup
CloudFormation - CREATE_FAILED - AWS::ApiGateway::RestApi - ApiGatewayRestApi
CloudFormation - CREATE_FAILED - AWS::Logs::LogGroup - UpdateLogGroup
CloudFormation - CREATE_FAILED - AWS::Logs::LogGroup - GetLogGroup
CloudFormation - CREATE_FAILED - AWS::Logs::LogGroup - CreateLogGroup
CloudFormation - UPDATE_ROLLBACK_IN_PROGRESS - AWS::CloudFormation::Stack - serverless-rest-api-with-dynamodb-rename-dev
CloudFormation - UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS - AWS::CloudFormation::Stack - serverless-rest-api-with-dynamodb-rename-dev
CloudFormation - DELETE_IN_PROGRESS - AWS::Logs::LogGroup - GetLogGroup
CloudFormation - DELETE_IN_PROGRESS - AWS::ApiGateway::RestApi - ApiGatewayRestApi
CloudFormation - DELETE_IN_PROGRESS - AWS::Logs::LogGroup - ListLogGroup
CloudFormation - DELETE_COMPLETE - AWS::Logs::LogGroup - CreateLogGroup
CloudFormation - DELETE_COMPLETE - AWS::DynamoDB::Table - TodosDynamoDbTable
CloudFormation - DELETE_COMPLETE - AWS::Logs::LogGroup - GetLogGroup
CloudFormation - DELETE_COMPLETE - AWS::Logs::LogGroup - UpdateLogGroup
CloudFormation - DELETE_COMPLETE - AWS::ApiGateway::RestApi - ApiGatewayRestApi
CloudFormation - DELETE_COMPLETE - AWS::Logs::LogGroup - ListLogGroup
CloudFormation - DELETE_COMPLETE - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - DELETE_COMPLETE - AWS::Logs::LogGroup - DeleteLogGroup
CloudFormation - UPDATE_ROLLBACK_COMPLETE - AWS::CloudFormation::Stack - serverless-rest-api-with-dynamodb-rename-dev
Serverless: Deployment failed!
 
  Serverless Error ---------------------------------------
 
     An error occurred while provisioning your stack: IamRoleLambdaExecution
     - 1 validation error detected: Value 'serverless-rest-api-with-dynamodb-rename-dev-us-east-1-lambdaRole'
     at 'roleName' failed to satisfy constraint: Member must
     have length less than or equal to 64.
 
  Stack Trace --------------------------------------------
 
ServerlessError: An error occurred while provisioning your stack: IamRoleLambdaExecution - 1 validation error detected: Value 'serverless-rest-api-with-dynamodb-rename-dev-us-east-1-lambdaRole' at 'roleName' failed to satisfy constraint: Member must have length less than or equal to 64.
    at provider.request.then (/usr/local/lib/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:112:33)
From previous event:
    at AwsDeploy.monitorStack (/usr/local/lib/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:29:12)
    at provider.request.then (/usr/local/lib/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:90:30)
From previous event:
    at AwsDeploy.update (/usr/local/lib/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:90:8)
From previous event:
    at AwsDeploy.BbPromise.bind.then.then (/usr/local/lib/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:111:12)
From previous event:
    at AwsDeploy.updateStack (/usr/local/lib/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:103:8)
From previous event:
    at Object.deploy:deploy [as fn] (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:55:10)
    at BbPromise.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:210:55)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:210:22)
    at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:225:17)
    at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:97:31)
    at serverless.init.then (/usr/local/lib/node_modules/serverless/bin/serverless:23:50)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       7.3.0
     Serverless Version: 1.11.0
```

**Comment by christophgysin** [comment]
Now the name is too long, try something shorter...

**Comment by waltermvp** [comment]
@christophgysin it worked 👍  thank you very much for your help. I'll close this issue now.

Unrelated: if I want to add an image to my todo object, can you point me to some examples that show the "proper" way of doing this? I would like to store the image on S3 and have the URL return as a field of the todo.

**Comment by christophgysin** [comment]
There are different ways to this. Pass it to the lambda, and have the lambda store it in S3. Or have the lambda create a pre-signed URL, pass it to the client, and let the client upload directly to S3.
