### ISSUE TITLE
All endpoints return {"message": "Internal server error"} on aws-node-rest-api-with-dynamodb

### ISSUE THREAD

**Issue by waltermvp** [serverless/examples#142]
@christophgysin ran into another issue. Sorry to keep bugging. 

**You can see that the example is successfully deployed, however, I immediately perform a curl to get all todos and it returns the error.**

```bash

waltermvp@Walters-MacBook-Pro:~/Development/Open/examples/aws-node-rest-api-with-dynamodb (master)$ SLS_DEBUG="*" sls deploy --verbose
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
CloudFormation - CREATE_IN_PROGRESS - AWS::CloudFormation::Stack - serverless-short-test2-dev
CloudFormation - CREATE_IN_PROGRESS - AWS::S3::Bucket - ServerlessDeploymentBucket
CloudFormation - CREATE_IN_PROGRESS - AWS::S3::Bucket - ServerlessDeploymentBucket
CloudFormation - CREATE_COMPLETE - AWS::S3::Bucket - ServerlessDeploymentBucket
CloudFormation - CREATE_COMPLETE - AWS::CloudFormation::Stack - serverless-short-test2-dev
Serverless: Stack create finished...
Serverless: Packaging service...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading function .zip files to S3...
Serverless: Uploading service .zip file to S3 (431.03 KB)...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
CloudFormation - CREATE_COMPLETE - AWS::CloudFormation::Stack - serverless-short-test2-dev
CloudFormation - UPDATE_IN_PROGRESS - AWS::CloudFormation::Stack - serverless-short-test2-dev
CloudFormation - CREATE_IN_PROGRESS - AWS::ApiGateway::RestApi - ApiGatewayRestApi
CloudFormation - CREATE_IN_PROGRESS - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - CreateLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - ListLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - UpdateLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::DynamoDB::Table - TodosDynamoDbTable
CloudFormation - CREATE_IN_PROGRESS - AWS::ApiGateway::RestApi - ApiGatewayRestApi
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - GetLogGroup
CloudFormation - CREATE_COMPLETE - AWS::ApiGateway::RestApi - ApiGatewayRestApi
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - CreateLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - UpdateLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::DynamoDB::Table - TodosDynamoDbTable
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - CreateLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - ListLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - UpdateLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - GetLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - GetLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - ListLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - DeleteLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - DeleteLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - DeleteLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::ApiGateway::Resource - ApiGatewayResourceTodos
CloudFormation - CREATE_IN_PROGRESS - AWS::ApiGateway::Resource - ApiGatewayResourceTodos
CloudFormation - CREATE_COMPLETE - AWS::ApiGateway::Resource - ApiGatewayResourceTodos
CloudFormation - CREATE_COMPLETE - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - CREATE_IN_PROGRESS - AWS::ApiGateway::Method - ApiGatewayMethodTodosOptions
CloudFormation - CREATE_IN_PROGRESS - AWS::ApiGateway::Resource - ApiGatewayResourceTodosIdVar
CloudFormation - CREATE_IN_PROGRESS - AWS::ApiGateway::Method - ApiGatewayMethodTodosOptions
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - DeleteLambdaFunction
CloudFormation - CREATE_COMPLETE - AWS::ApiGateway::Method - ApiGatewayMethodTodosOptions
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - UpdateLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - ListLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - GetLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - CreateLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::ApiGateway::Resource - ApiGatewayResourceTodosIdVar
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - DeleteLambdaFunction
CloudFormation - CREATE_COMPLETE - AWS::ApiGateway::Resource - ApiGatewayResourceTodosIdVar
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Function - DeleteLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - UpdateLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - ListLambdaFunction
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Function - UpdateLambdaFunction
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Function - ListLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - CreateLambdaFunction
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Function - CreateLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::ApiGateway::Method - ApiGatewayMethodTodosIdVarOptions
CloudFormation - CREATE_IN_PROGRESS - AWS::ApiGateway::Method - ApiGatewayMethodTodosIdVarDelete
CloudFormation - CREATE_IN_PROGRESS - AWS::ApiGateway::Method - ApiGatewayMethodTodosIdVarOptions
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Permission - DeleteLambdaPermissionApiGateway
CloudFormation - CREATE_IN_PROGRESS - AWS::ApiGateway::Method - ApiGatewayMethodTodosIdVarDelete
CloudFormation - CREATE_IN_PROGRESS - AWS::ApiGateway::Method - ApiGatewayMethodTodosGet
CloudFormation - CREATE_COMPLETE - AWS::ApiGateway::Method - ApiGatewayMethodTodosIdVarDelete
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - ListLambdaVersionvFSmJAY4jqmJqLz3Nj1bDHiSn2Hy2jLHIlL4w9hCbQ
CloudFormation - CREATE_COMPLETE - AWS::ApiGateway::Method - ApiGatewayMethodTodosIdVarOptions
CloudFormation - CREATE_IN_PROGRESS - AWS::ApiGateway::Method - ApiGatewayMethodTodosGet
CloudFormation - CREATE_IN_PROGRESS - AWS::ApiGateway::Method - ApiGatewayMethodTodosIdVarPut
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Permission - DeleteLambdaPermissionApiGateway
CloudFormation - CREATE_IN_PROGRESS - AWS::ApiGateway::Method - ApiGatewayMethodTodosIdVarPut
CloudFormation - CREATE_COMPLETE - AWS::ApiGateway::Method - ApiGatewayMethodTodosGet
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - UpdateLambdaVersionvFSmJAY4jqmJqLz3Nj1bDHiSn2Hy2jLHIlL4w9hCbQ
CloudFormation - CREATE_COMPLETE - AWS::ApiGateway::Method - ApiGatewayMethodTodosIdVarPut
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - ListLambdaVersionvFSmJAY4jqmJqLz3Nj1bDHiSn2Hy2jLHIlL4w9hCbQ
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Version - ListLambdaVersionvFSmJAY4jqmJqLz3Nj1bDHiSn2Hy2jLHIlL4w9hCbQ
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - UpdateLambdaVersionvFSmJAY4jqmJqLz3Nj1bDHiSn2Hy2jLHIlL4w9hCbQ
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - GetLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Permission - ListLambdaPermissionApiGateway
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Version - UpdateLambdaVersionvFSmJAY4jqmJqLz3Nj1bDHiSn2Hy2jLHIlL4w9hCbQ
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Function - GetLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Permission - ListLambdaPermissionApiGateway
CloudFormation - CREATE_IN_PROGRESS - AWS::ApiGateway::Method - ApiGatewayMethodTodosPost
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - DeleteLambdaVersionvFSmJAY4jqmJqLz3Nj1bDHiSn2Hy2jLHIlL4w9hCbQ
CloudFormation - CREATE_IN_PROGRESS - AWS::ApiGateway::Method - ApiGatewayMethodTodosPost
CloudFormation - CREATE_COMPLETE - AWS::ApiGateway::Method - ApiGatewayMethodTodosPost
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - DeleteLambdaVersionvFSmJAY4jqmJqLz3Nj1bDHiSn2Hy2jLHIlL4w9hCbQ
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Permission - UpdateLambdaPermissionApiGateway
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - CreateLambdaVersionvFSmJAY4jqmJqLz3Nj1bDHiSn2Hy2jLHIlL4w9hCbQ
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Version - DeleteLambdaVersionvFSmJAY4jqmJqLz3Nj1bDHiSn2Hy2jLHIlL4w9hCbQ
CloudFormation - CREATE_COMPLETE - AWS::DynamoDB::Table - TodosDynamoDbTable
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Permission - UpdateLambdaPermissionApiGateway
CloudFormation - CREATE_IN_PROGRESS - AWS::ApiGateway::Method - ApiGatewayMethodTodosIdVarGet
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Permission - CreateLambdaPermissionApiGateway
CloudFormation - CREATE_IN_PROGRESS - AWS::ApiGateway::Method - ApiGatewayMethodTodosIdVarGet
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Permission - CreateLambdaPermissionApiGateway
CloudFormation - CREATE_COMPLETE - AWS::ApiGateway::Method - ApiGatewayMethodTodosIdVarGet
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Permission - DeleteLambdaPermissionApiGateway
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - CreateLambdaVersionvFSmJAY4jqmJqLz3Nj1bDHiSn2Hy2jLHIlL4w9hCbQ
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Version - CreateLambdaVersionvFSmJAY4jqmJqLz3Nj1bDHiSn2Hy2jLHIlL4w9hCbQ
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - GetLambdaVersionvFSmJAY4jqmJqLz3Nj1bDHiSn2Hy2jLHIlL4w9hCbQ
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Permission - GetLambdaPermissionApiGateway
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Permission - ListLambdaPermissionApiGateway
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Permission - GetLambdaPermissionApiGateway
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - GetLambdaVersionvFSmJAY4jqmJqLz3Nj1bDHiSn2Hy2jLHIlL4w9hCbQ
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Version - GetLambdaVersionvFSmJAY4jqmJqLz3Nj1bDHiSn2Hy2jLHIlL4w9hCbQ
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Permission - UpdateLambdaPermissionApiGateway
CloudFormation - CREATE_IN_PROGRESS - AWS::ApiGateway::Deployment - ApiGatewayDeployment1493232080255
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Permission - CreateLambdaPermissionApiGateway
CloudFormation - CREATE_IN_PROGRESS - AWS::ApiGateway::Deployment - ApiGatewayDeployment1493232080255
CloudFormation - CREATE_COMPLETE - AWS::ApiGateway::Deployment - ApiGatewayDeployment1493232080255
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Permission - GetLambdaPermissionApiGateway
CloudFormation - UPDATE_COMPLETE_CLEANUP_IN_PROGRESS - AWS::CloudFormation::Stack - serverless-short-test2-dev
CloudFormation - UPDATE_COMPLETE - AWS::CloudFormation::Stack - serverless-short-test2-dev
Serverless: Stack update finished...
Service Information
service: serverless-short-test2
stage: dev
region: us-east-1
api keys:
  None
endpoints:
  POST - https://yhhzsbppdj.execute-api.us-east-1.amazonaws.com/dev/todos
  GET - https://yhhzsbppdj.execute-api.us-east-1.amazonaws.com/dev/todos
  GET - https://yhhzsbppdj.execute-api.us-east-1.amazonaws.com/dev/todos/{id}
  PUT - https://yhhzsbppdj.execute-api.us-east-1.amazonaws.com/dev/todos/{id}
  DELETE - https://yhhzsbppdj.execute-api.us-east-1.amazonaws.com/dev/todos/{id}
functions:
  create: serverless-short-test2-dev-create
  list: serverless-short-test2-dev-list
  get: serverless-short-test2-dev-get
  update: serverless-short-test2-dev-update
  delete: serverless-short-test2-dev-delete

Stack Outputs
DeleteLambdaFunctionQualifiedArn: arn:aws:lambda:us-east-1:056882338896:function:serverless-short-test2-dev-delete:1
CreateLambdaFunctionQualifiedArn: arn:aws:lambda:us-east-1:056882338896:function:serverless-short-test2-dev-create:1
GetLambdaFunctionQualifiedArn: arn:aws:lambda:us-east-1:056882338896:function:serverless-short-test2-dev-get:1
UpdateLambdaFunctionQualifiedArn: arn:aws:lambda:us-east-1:056882338896:function:serverless-short-test2-dev-update:1
ListLambdaFunctionQualifiedArn: arn:aws:lambda:us-east-1:056882338896:function:serverless-short-test2-dev-list:1
ServiceEndpoint: https://yhhzsbppdj.execute-api.us-east-1.amazonaws.com/dev
ServerlessDeploymentBucketName: serverless-short-test2-d-serverlessdeploymentbuck-1lin9n3dy4vvz

waltermvp@Walters-MacBook-Pro:~/Development/Open/examples/aws-node-rest-api-with-dynamodb (master)$ curl https://yhhzsbppdj.execute-api.us-east-1.amazonaws.com/dev/todos
{"message": "Internal server error"}waltermvp@Walters-MacBook-Pro:~/Development/Open/examples/aws-node-rest-api-with-dynamodb (master)$ 

```

**Comment by christophgysin** [comment]
Check the CloudWatch log streams for errors:

$ serverless logs -f list

**Comment by waltermvp** [comment]
Thanks for your patience and very prompt reply (im an iOS developer just starting with backend all because of your incredible work here).

```bash 
waltermvp@Walters-MacBook-Pro:~/Development/Open/examples/aws-node-rest-api-with-dynamodb (master)$ serverless logs -f list
START RequestId: 294e56d8-2ab0-11e7-911d-2b605664f737 Version: $LATEST
module initialization error: TypeError
    at Object.<anonymous> (/var/task/todos/list.js:5:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
END RequestId: 294e56d8-2ab0-11e7-911d-2b605664f737
REPORT RequestId: 294e56d8-2ab0-11e7-911d-2b605664f737	Duration: 5.76 ms	Billed Duration: 100 ms 	Memory Size: 1024 MB	Max Memory Used: 24 MB	

waltermvp@Walters-MacBook-Pro:~/Development/Open/examples/aws-node-rest-api-with-dynamodb (master)$ 
```

**Comment by waltermvp** [comment]
`_extensions..js` does not look right

**Comment by christophgysin** [comment]
I can't reproduce this, works normally for me. The error seems to come from:
https://github.com/serverless/examples/blob/master/aws-node-rest-api-with-dynamodb/todos/list.js#L5
That is simply using the aws-sdk, which is provided by the lambda environment.

**Comment by christophgysin** [comment]
Did you make any modifications to the example?

**Comment by waltermvp** [comment]
I have only modified the service name. I'll investigate further tonight to see if I can figure it out myself. Thanks again, your the best🥇

**Comment by MathiasBerwig** [comment]
Same problem here. Solved removing `uuid` dependency and receiving ids from the app. It's not the best approach but works for testing purposes.

**Comment by waltermvp** [comment]
@MathiasBerwig  how did you generate the `uuid` is there a native function for this?

**Comment by MathiasBerwig** [comment]
@waltermvp at this moment I'm using an Android app as client, so in the constructor of a new todo I simply call `this.id = java.util.UUID.randomUUID().toString();`.

**Comment by christophgysin** [comment]
I don't understand how uuid causes the problem. Could you elaborate?

@waltermvp Could you simply try removing uuid from packages.json, delete node_modules, run "npm i" and deploy again? uuid is only needed for the `create` method, so `list` should still work.

**Comment by waltermvp** [comment]
@christophgysin I made sure the buckets were removed and cleaned the state of the working copy. The project is working now. Never got to test without the UDID dependency so I  don't think that is related. Not sure exactly what was causing this issue but after the clean checkout its working

**Comment by waltermvp** [comment]
@christophgysin @MathiasBerwig 
So the issue was not with `uuid` but due to not running `npm install` before deployment.
