### ISSUE TITLE
aws-node-rest-api-with-dynamodb-and-offline always returns an Error 

### ISSUE THREAD

**Issue by waltermvp** [serverless/examples#146]
I'm having issues with the offline plugin. Is this normal? `Error: connect ECONNREFUSED 127.0.0.1:8000`.  Not sure since the local host is 3000

```bash

waltermvp@Walters-MacBook-Pro:~/Development/Open/examples/aws-node-rest-api-with-dynamodb-and-offline (master)$ sls offline
Serverless: Starting Offline: dev/us-east-1.

Serverless: Routes for create:
Serverless: POST /todos

Serverless: Routes for list:
Serverless: GET /todos

Serverless: Routes for get:
Serverless: GET /todos/{id}

Serverless: Routes for update:
Serverless: PUT /todos/{id}

Serverless: Routes for delete:
Serverless: DELETE /todos/{id}

Serverless: Offline listening on http://localhost:3000

Serverless: GET /todos (λ: list)
Serverless: The first request might take a few extra seconds
Serverless: 
{ Error: connect ECONNREFUSED 127.0.0.1:8000
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
  message: 'connect ECONNREFUSED 127.0.0.1:8000',
  code: 'NetworkingError',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 8000,
  region: 'localhost',
  hostname: 'localhost',
  retryable: true,
  time: 2017-05-01T15:17:51.864Z }
Serverless: Failure: Couldn't fetch the todos.
Serverless: Replying 200

```

**Comment by waltermvp** [comment]
Me again :/ @christophgysin

**Comment by amslezak** [comment]
I had this issue as well.  You have to use the command `serverless offline start`.

Then, load another terminal window, load the table schema into dynamodb via `serverless dynamodb migrate`.

Added pull request https://github.com/serverless/examples/pull/147

**Comment by waltermvp** [comment]
@amslezak that fixed the issue. Thanks!

**Comment by ozbillwang** [comment]
@waltermvp 

when i run `serverless offline start`, always get below error

```
$ sls offline start
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn java ENOENT
    at exports._errnoException (util.js:1020:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:197:32)
    at onErrorNT (internal/child_process.js:376:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```
My environment
```
  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           6.11.3
     Serverless Version:     1.23.0
```

**Comment by christophgysin** [comment]
Please open a new issue, don't hijack an old issue. Thanks!
