### ISSUE TITLE
aws-node-rest-api-with-dynamodb-and-offline -  throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by ozbillwang** [serverless/examples#197]
When trying the example: `aws-node-rest-api-with-dynamodb-and-offline`, I run `serverless offline start`, always get below error. Any hints for me?

```
$ sls offline start
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn java ENOENT
    at exports._errnoException (util.js:1020:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:197:32)
    at onErrorNT (internal/child_process.js:376:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

My environment
```

  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           6.11.3
     Serverless Version:     1.23.0
```

**Comment by christophgysin** [comment]
Do you have java installed?

**Comment by ozbillwang** [comment]
@christophgysin 

No, I run a new Ubuntu server without java. Will install it and try again. 

Thanks a lot.

**Comment by ozbillwang** [comment]
Thanks, @christophgysin 

I play around with the offline DynamoDB, very nice. 

I needn't run `serverless dynamodb migrate`, get resources in use error. The curl tests still go well.

```
$ serverless dynamodb migrate
Serverless: DynamoDB - Error -

  Resource In Use Exception ------------------------------

  Cannot create preexisting table
```
