### ISSUE TITLE
serverless syncToS3 Cannot read property 'OutputValue' of undefined

### ISSUE THREAD

**Issue by nolafs** [serverless/examples#217]
Hi,

The syncToS3 worked perfectly fine all day and today it won't sync anymore. Nothing has changed on in serverless.yml. No idea what is causing it. I have delete the stack and deployed again but still getting the error.

Cheers
Olaf

**Comment by jpswade** [comment]
```
Unhandled rejection TypeError: Cannot read property 'OutputValue' of undefined
    at provider.request.then (.../node_modules/serverless-single-page-app-plugin/index.js:51:22)
From previous event:
    at ServerlessPlugin.getDescribeStacksOutput (.../node_modules/serverless-single-page-app-plugin/index.js:48:8)
    at ServerlessPlugin.syncDirectory (.../node_modules/serverless-single-page-app-plugin/index.js:57:10)
    at BbPromise.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:360:55)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:360:22)
    at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:391:17)
    at variables.populateService.then (/usr/local/lib/node_modules/serverless/lib/Serverless.js:99:33)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:86:74)
    at serverless.init.then (/usr/local/lib/node_modules/serverless/bin/serverless:39:50)
```

**Comment by Rakesh201180** [comment]
I am also getting same error,any update on this

**Comment by daviskoh** [comment]
Indeed [WebApp is relied on as a key](https://github.com/serverless/examples/blob/master/aws-node-single-page-app-via-cloudfront/serverless-single-page-app-plugin/index.js#L72)
