### ISSUE TITLE
aws-python-pynamodb-s3-sigurl: Cannot read property 'toString' of null

### ISSUE THREAD

**Issue by john-aws** [serverless/examples#364]
Hitting the following error when deploying aws-python-pynamodb-s3-sigurl:

```
u101@mbp-u101:~/examples/aws-python-pynamodb-s3-sigurl$ SLS_DEBUG=* sls deploy
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command requirements
Serverless: Load command requirements:clean
Serverless: Load command requirements:install
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Parsing Python requirements.txt
Serverless: Installing required Python packages for runtime python3.6...

  Type Error ---------------------------------------------

  Cannot read property 'toString' of null

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

TypeError: Cannot read property 'toString' of null
    at BbPromise (/Users/u101/examples/aws-python-pynamodb-s3-sigurl/node_modules/serverless-python-requirements/index.js:93:31)
    at ServerlessPythonRequirements.installRequirements (/Users/u101/examples/aws-python-pynamodb-s3-sigurl/node_modules/serverless-python-requirements/index.js:84:12)
    at ServerlessPythonRequirements.packRequirements (/Users/u101/examples/aws-python-pynamodb-s3-sigurl/node_modules/serverless-python-requirements/index.js:130:17)
From previous event:
    at PluginManager.invoke (/Users/u101/.nvm/versions/node/v8.10.0/lib/node_modules/serverless/lib/classes/PluginManager.js:407:22)
    at PluginManager.spawn (/Users/u101/.nvm/versions/node/v8.10.0/lib/node_modules/serverless/lib/classes/PluginManager.js:425:17)
    at Deploy.BbPromise.bind.then (/Users/u101/.nvm/versions/node/v8.10.0/lib/node_modules/serverless/lib/plugins/deploy/deploy.js:117:50)
From previous event:
    at Object.before:deploy:deploy [as hook] (/Users/u101/.nvm/versions/node/v8.10.0/lib/node_modules/serverless/lib/plugins/deploy/deploy.js:107:10)
    at BbPromise.reduce (/Users/u101/.nvm/versions/node/v8.10.0/lib/node_modules/serverless/lib/classes/PluginManager.js:407:55)
From previous event:
    at PluginManager.invoke (/Users/u101/.nvm/versions/node/v8.10.0/lib/node_modules/serverless/lib/classes/PluginManager.js:407:22)
    at PluginManager.run (/Users/u101/.nvm/versions/node/v8.10.0/lib/node_modules/serverless/lib/classes/PluginManager.js:438:17)
    at variables.populateService.then.then (/Users/u101/.nvm/versions/node/v8.10.0/lib/node_modules/serverless/lib/Serverless.js:114:33)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at Serverless.run (/Users/u101/.nvm/versions/node/v8.10.0/lib/node_modules/serverless/lib/Serverless.js:101:6)
    at serverless.init.then (/Users/u101/.nvm/versions/node/v8.10.0/lib/node_modules/serverless/bin/serverless:43:28)
    at /Users/u101/.nvm/versions/node/v8.10.0/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:111:16
    at /Users/u101/examples/aws-python-pynamodb-s3-sigurl/node_modules/graceful-fs/graceful-fs.js:43:10
    at /Users/u101/.nvm/versions/node/v8.10.0/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at initializeErrorReporter.then (/Users/u101/.nvm/versions/node/v8.10.0/lib/node_modules/serverless/bin/serverless:43:6)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at /Users/u101/.nvm/versions/node/v8.10.0/lib/node_modules/serverless/bin/serverless:28:46
    at Object.<anonymous> (/Users/u101/.nvm/versions/node/v8.10.0/lib/node_modules/serverless/bin/serverless:67:4)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.10.0
     Serverless Version:     1.38.0
```

**Comment by nebsi04** [comment]
I had the exact error: Cannot read property of 'toString' of null.

I'm still having issues but I was able to get past the above error by updating the serverless-python-requirements plugin to the latest version.

Now I'm getting this error: sig-s3-uploader already exists.

For the sig-s3-uploader already exists error, I've tried the 'sls remove' command and even tried removing the s3 bucket asset and CloudFormation stack manually. I've also tried changing the stage value to 'dev' in the serverless.yml file.

When I review the full error output, it looks like the deployment process might be trying to create the bucket object twice: once in the beginning and once at the end. I'm a little new to this so I'm not sure if that really is the issue here. It does fail on bucket creation though.

Try to update your serverless-python-requirements package and see if you have the same error as me.

**Comment by somq** [comment]
Something is broken related to python bin path I guess reading [this issue](https://github.com/UnitedIncome/serverless-python-requirements/issues/72)

I just upgraded `serverless-python-requirements` to latest and wrapped python process inside pipenv and it worked flawlessly.

package.json

```json
`{
  "name": "aws-python-pynamodb-s3-sigurl",
  "version": "1.0.0",
  "description": "Serverless signed uploader REST API using pynamodb, s3 generated events, custom log format, and DRY serverless.yml with custom section",
  "author": "Bruce Edge",
  "license": "MIT",
  "dependencies": {
    "serverless-python-requirements": "^5.0.1"
  }
}
```

```yaml
# ...
custom:
  pythonRequirements:
    usePipenv: true
```
