### ISSUE TITLE
aws-node-single-page-app-via-cloudfront deploy error

### ISSUE THREAD

**Issue by herrsergio** [serverless/examples#39]
I get the following error when I make the "serverless deploy":

```
  Syntax Error -------------------------------------------
 
     Unexpected token )
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Stack Trace --------------------------------------------
 
SyntaxError: Unexpected token )
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /usr/lib/node_modules/serverless/lib/classes/PluginManager.js:59:22
    at Array.forEach (native)
    at PluginManager.loadPlugins (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:58:13)
    at PluginManager.loadServicePlugins (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:86:10)
    at PluginManager.loadAllPlugins (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:54:10)
    at /usr/lib/node_modules/serverless/lib/Serverless.js:64:28
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
 
     Please report this error. We think it might be a bug.
 
  Your Environment Information -----------------------------
     OS:                 linux
     Node Version:       4.6.1
     Serverless Version: 1.3.0
```

**Comment by SharathHuddar** [comment]
Same issue here

**Comment by SharathHuddar** [comment]
@herrsergio . The plugin is written with es6 syntax, hence the error.

**Comment by nikgraf** [comment]
@herrsergio @SharathHuddar we merged a fix, can you let me know if it works for you now?

**Comment by herrsergio** [comment]
Thank you @nikgraf , it's working now.
