### ISSUE TITLE
aws-node-puppeteer - {"message": "Internal server error"}

### ISSUE THREAD

**Issue by unickq** [serverless/examples#482]
Cloned **aws-node-puppeteer** repo.

npm i
serverless offline - works as expected
serverless deploy - `{"message": "Internal server error"}`

what's wrong?

Thanks

**Comment by michaldolnik** [comment]
> Cloned **aws-node-puppeteer** repo.
> 
> npm i
> serverless offline - works as expected
> serverless deploy - `{"message": "Internal server error"}`
> 
> what's wrong? any additional config required?
> 
> Thanks

I have the same problem...

**Comment by mvaneijgen** [comment]
Same here!

Here is the Cloud watch error I get 

https://gist.github.com/mvaneijgen/c4356a8e7dab84ed8abf80d33604f7d1

**Comment by JaredReando** [comment]
Same here! 

I tried adding a `--headless` flag in "/node-modules/@serverless-chrome/lamba/dis/bundle.es.js/" around lines 338 / 349 after seeing that referenced in an older issue thread, but still no dice.

All I've done is clone / setup / deploy, so no other custom configs could be messing with the mojo....

**Comment by demilp** [comment]
Same here.
Here is my log
`ERROR   Uncaught Exception      {"errorType":"Error","errorMessage":"spawn /var/task/node_modules/@serverless-chrome/lambda/dist/headless-chromium EACCES","code":"EACCES","errno":"EACCES","syscall":"spawn /var/task/node_modules/@serverless-chrome/lambda/dist/headless-chromium","path":"/var/task/node_modules/@serverless-chrome/lambda/dist/headless-chromium","spawnargs":["--disable-dev-shm-usage","--disable-gpu","--single-process","--no-zygote","--no-sandbox","--remote-debugging-port=9222","--user-data-dir=/tmp/chrome.AUlavv8","--disable-setuid-sandbox","--disable-dev-shm-usage","--disable-gpu","--single-process","--no-zygote","--no-sandbox","about:blank"],"stack":["Error: spawn /var/task/node_modules/@serverless-chrome/lambda/dist/headless-chromium EACCES","    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)","    at onErrorNT (internal/child_process.js:469:16)","    at processTicksAndRejections (internal/process/task_queues.js:84:21)"]}
END RequestId: 99eb7477-0fa6-4919-a881-70715199a495
REPORT RequestId: 99eb7477-0fa6-4919-a881-70715199a495  Duration: 94.39 ms      Billed Duration: 100 ms Memory Size: 1024 MB                 Max Memory Used: 26 MB

Unknown application error occurred`

**Comment by YuK1Game** [comment]
mee too... 🥺

**Comment by tiboprea** [comment]
I'm experiencing the same issues. Has anyone managed to find a fix?

**Comment by Azsael** [comment]
I believe this is linked to this issue (https://github.com/adieuadieu/serverless-chrome/issues/240)

**Comment by botoxparty** [comment]
Also getting the same thing :-/

**Comment by hndr91** [comment]
I've got the same issue

**Comment by mzane42** [comment]
Up !

**Comment by Liu-huaicheng** [comment]
same issue

**Comment by michaldolnik** [comment]
Actually I have ended up with using AWS Fargate for my use case. As long as AWS lamba has 15 mins runtime, it's not useful for my use case anymore...

**Comment by hir09** [comment]
const puppeteer = require('puppeteer');

(async () => {
//const browser = await puppeteer.launch({headless: false, defaultViewport: null});
const browser = await puppeteer.launch({defaultViewport: null});
const page = await browser.newPage();
await page.setViewport({ width: 1920, height: 1080});

await page.goto('https://www.rezultati.com/', {waitUntil: 'networkidle2'});

const firstTeamName = await page.evaluate(() => {
let a = document.querySelector("#g_1_KAjFXPMu > div.event__participant.event__participant--home");
return a.innerText;
})

console.log(firstTeamName)

await browser.close();
})();

**Comment by hir09** [comment]
above is my script and blow is my error....please help , any hero expert here   :


i followed this

https://www.serverless.com/examples/aws-node-puppeteer

2021-01-29T06:21:00.312Z 0333c6a5-06af-4a23-a37f-0f0ef8a675b4 ERROR Invoke Error {
"errorType": "Error",
"errorMessage": "Unable to start Chrome. If you have the DEBUG env variable set,there will be more in the logs.",
"stack": [
"Error: Unable to start Chrome. If you have the DEBUG env variable set,there will be more in the logs.",
" at /var/task/node_modules/@serverless-chrome/lambda/dist/bundle.cjs.js:376:13",
" at Generator.throw (<anonymous>)",
" at step (/var/task/node_modules/@serverless-chrome/lambda/dist/bundle.cjs.js:311:193)",
" at /var/task/node_modules/@serverless-chrome/lambda/dist/bundle.cjs.js:311:404",
" at processTicksAndRejections (internal/process/task_queues.js:97:5)"
]
}

and this is the error

**Comment by yanekyuk** [comment]
Same here. Also, putting `DEBUD: "*"` seems to break the logs page by causing infinite loading. I have tried disabling `--v=99` flag on `node_modules/@serverless-chrome/lambda/dist/bundle.es.js` as it was suggested on multiple issues.

**Comment by chicomcastro** [comment]
It's still happening :(

**Comment by sbbeez** [comment]
+1

**Comment by karchx** [comment]
Good evening, did anyone have a solution for this?
